What is numpy?

NumPy is the fundamental package for scientific computing in Python. It is a Python library that provides a multidimensional array object, various derived objects (such as masked arrays and matrices), and an assortment of routines for fast operations on arrays, including mathematical, logical, shape manipulation, sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical operations, random simulation and much more.

At the core of the NumPy package, is the ndarray object. This encapsulates n-dimensional arrays of homogeneous data types
Numpy Arrays Vs Python Sequences

    NumPy arrays have a fixed size at creation, unlike Python lists (which can grow dynamically). Changing the size of an ndarray will create a new array and delete the original.

    The elements in a NumPy array are all required to be of the same data type, and thus will be the same size in memory.

    NumPy arrays facilitate advanced mathematical and other types of operations on large numbers of data. Typically, such operations are executed more efficiently and with less code than is possible using Python’s built-in sequences.

    A growing plethora of scientific and mathematical Python-based packages are using NumPy arrays; though these typically support Python-sequence input, they convert such input to NumPy arrays prior to processing, and they often output NumPy arrays.



# Creating Numpy Arrays

In [1]:
# np.array 1D or Vector
import numpy as np

a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
# check data type
type(a)

numpy.ndarray

In [6]:
# 2D or Matrix
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
# 3D or Tesnsor
c = np.array([[[1,2,3],[3,4,5],[6,7,8]]])
print(c)

[[[1 2 3]
  [3 4 5]
  [6 7 8]]]


In [10]:
# dtype
d = np.array([1,2,3], dtype = float)
d

array([1., 2., 3.])

In [11]:
d = np.array([1,2,3], dtype = bool)
d

array([ True,  True,  True])

In [12]:
d = np.array([1,2,3], dtype = complex)
d

array([1.+0.j, 2.+0.j, 3.+0.j])

In [13]:
# np.arange 1-10
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [14]:
# np.arange   
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [16]:
# with reshape  | 2D array with 5 rows 2 cols
np.arange(1,11).reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [17]:
np.arange(1,11).reshape(2,5) # 2 rows 5 cols

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [19]:
np.arange(1,13).reshape(3,4)       # be careful with product like 3 x 4 = 12

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
# with reshape
np.arange(16).reshape(2,2,2,2)

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [21]:
# np.ones it will take shape and all item will be 1 | use case to initilize arrays
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
# np.zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [24]:
# np.random  | it's generate random nuber between 0-1
np.random.random((3,4))

array([[0.57028213, 0.23302301, 0.20953107, 0.32793743],
       [0.00602939, 0.82294206, 0.94147555, 0.69100624],
       [0.79632199, 0.93202867, 0.41423783, 0.28966294]])

In [25]:
# np.linspace-linear space | here we gave (lower_range,upper_range,num_of_items)|it's generate points in equal range in given distance
np.linspace(-10,10,10)

array([-10.        ,  -7.77777778,  -5.55555556,  -3.33333333,
        -1.11111111,   1.11111111,   3.33333333,   5.55555556,
         7.77777778,  10.        ])

In [26]:
# np.identity | to create identity matrix - diagnal item 1 rest 0
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [4]:
a1 =np.arange(10)
a2 = np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [5]:
# ndim - Number of dimension
a1.ndim


1

In [6]:
a2.ndim

2

In [7]:
a3.ndim

3

In [9]:
# shape shows no of rows and cols
a1.shape           # shows it's a 1d numpy array


(10,)

In [10]:
a2.shape

(3, 4)

In [11]:
a3.shape      # says 2 2d array, num of rows 2, num of cols 2

(2, 2, 2)

In [12]:
# size -> shows no of items
a1.size

10

In [13]:
a2.size

12

In [14]:
a3.size

8

In [15]:
# itemsize -> each item occupies memory size
a1.itemsize          # 4 bites

4

In [16]:
a2.itemsize         # 8 bites

8

In [17]:
a3.itemsize         # 4 bites

4

In [18]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int32


# Changing Datatype

In [20]:
# astype -> helps to change datatype int32 , int64, float
print(a3)
print(a3.dtype)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]
int32


In [24]:
# changing a3 int32 -> int64
a3.astype(np.int64)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int64)

# Array Operations

In [26]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

print(a1)
print()
print(a2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [27]:
# scaler operation -> single np array operate with scaler i.e numbers
a1 * 2  # Matrix x scaler | all item inside matrix product with 2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [28]:
a1 + 2 

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [29]:
a1 - 2 

array([[-2, -1,  0,  1],
       [ 2,  3,  4,  5],
       [ 6,  7,  8,  9]])

In [30]:
a1 / 2 

array([[0. , 0.5, 1. , 1.5],
       [2. , 2.5, 3. , 3.5],
       [4. , 4.5, 5. , 5.5]])

In [31]:
a1 ** 2

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [32]:
a1 % 2

array([[0, 1, 0, 1],
       [0, 1, 0, 1],
       [0, 1, 0, 1]], dtype=int32)

In [33]:
# relational
a2 > 5            # checking number are greater than 5 inside matrix

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [34]:
a2 > 25  

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [35]:
a2 == 15  

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [36]:
# vector operations -> when we perform operator on 2 np array
a1 + a2   # since both matrix shape is same so we can easyly perform it

array([[12, 14, 16, 18],
       [20, 22, 24, 26],
       [28, 30, 32, 34]])

In [38]:
a1 * a2           # can do all the operator + - * ** / %

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array Functions

In [40]:
a1 = np.random.random((3,3)) # genearte random number between 0-1 3 rows 3 cols
a1

array([[0.69544546, 0.54317754, 0.01367458],
       [0.11733355, 0.65006175, 0.64644621],
       [0.92217909, 0.44794828, 0.90173782]])

In [41]:
# rounding a1 with multplying 100 tomake it 1-100
a1 = np.round(a1 * 100)
a1

array([[70., 54.,  1.],
       [12., 65., 65.],
       [92., 45., 90.]])

In [43]:
# max
np.max(a1)

92.0

In [44]:
# min
np.min(a1)

1.0

In [46]:
# sum
np.sum(a1)

494.0

In [47]:
# prod
np.product(a1)

71407299600000.0

In [48]:
# till now we take minimum from whole arrray now suppose we want row wise
# 0 -> col and 1 -> row
np.min(a1, axis=1)

array([ 1., 12., 45.])

In [49]:
# column wise min
np.min(a1, axis = 0)

array([12., 45.,  1.])

In [50]:
np.max(a1, axis=1) # row wise max

array([70., 65., 92.])

In [51]:
np.max(a1, axis=0) # col wise max

array([92., 65., 90.])

In [52]:
# mean/median/std/var
np.mean(a1)

54.888888888888886

In [54]:
np.median(a1)

65.0

In [55]:
np.std(a1)

29.59896561422542

In [56]:
np.var(a1)

876.0987654320987

In [57]:
np.mean(a1, axis = 1) #  can also use row wise mean

array([41.66666667, 47.33333333, 75.66666667])

In [58]:
np.mean(a1, axis = 0) #  can also use col wise mean

array([58.        , 54.66666667, 52.        ])

In [59]:
# trigonomoetric functions
np.sin(a1)

array([[ 0.77389068, -0.55878905,  0.84147098],
       [-0.53657292,  0.82682868,  0.82682868],
       [-0.77946607,  0.85090352,  0.89399666]])

In [62]:
# dot product  -> if first matrix num of cols == second matrix no of rows then only dot product possible
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

print(a2)
print()
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [63]:
np.dot(a2,a3)   # here a2 = (3,4)  a3 = (4,3) hence dot product possible -> (3,3)

array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [65]:
# log and exponents
np.log(a1)

array([[4.24849524, 3.98898405, 0.        ],
       [2.48490665, 4.17438727, 4.17438727],
       [4.52178858, 3.80666249, 4.49980967]])

In [66]:
np.exp(a1)

array([[2.51543867e+30, 2.83075330e+23, 2.71828183e+00],
       [1.62754791e+05, 1.69488924e+28, 1.69488924e+28],
       [9.01762841e+39, 3.49342711e+19, 1.22040329e+39]])

In [78]:
# round/floor/ceil
np.round(np.random.random((2,3))*100)   # round func round it to nearest integer 

array([[82., 66., 62.],
       [84., 36., 89.]])

In [79]:
np.floor(np.random.random((2,3))*100) # floor 6.9 -> 6 go backward

array([[90., 26.,  0.],
       [30., 47., 54.]])

In [80]:
np.ceil(np.random.random((2,3))*100) # floor 6.1 -> 7 go forward

array([[49.,  1., 63.],
       [12.,  5.,  7.]])

# Indexing and Slicing

In [81]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

print(a1)
print()
print(a2)
print()
print(a3)

[0 1 2 3 4 5 6 7 8 9]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]]


In [82]:
# indexing
# get last item from a1
a1[-1]

9

In [85]:
# get 6 from a2 i.e 2D array
a2[1,2] # first give row,col[row,col]

6

In [86]:
# get 11 from a2 i.e 2D array
a2[2,3]

11

In [89]:
# get 4 from a2 i.e 2D array
a2[1,0]

4

In [91]:
# get 5 from a3 i.e 3D array
a3[1,0,1]   # give (2d path, row, col)

5

In [93]:
# get 2 from a3 i.e 3D array
a3[0,1,0]

2

In [94]:
# get 2 from a3 i.e 3D array
a3[0,0,0]

0

In [95]:
# get 6 from a3 i.e 3D array
a3[1,1,0]

6

In [97]:
# slicing -> fetch multiple item
# get 2,3,4 from a1 1D array
a1[2:5]

array([2, 3, 4])

In [100]:
# get 1st row from a2
a2[0,:]   # (1st row, all column of first row)

array([0, 1, 2, 3])

In [106]:
# get 3rd column 2 6 10
a2[:,2]           (all rows, 3rd col)

array([ 2,  6, 10])

In [108]:
# get 5 6 9 10
a2[1:3,1:3]

array([[ 5,  6],
       [ 9, 10]])

In [121]:
# get 0 3 8 11
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [130]:
# get 1 3 9 11
a2[::2,1::2]

array([[ 1,  3],
       [ 9, 11]])

In [132]:
# get 4 7
a2[1,::3]

array([4, 7])

In [134]:
# get 1 2 3 5 6 7
a2[:2,1:]

array([[1, 2, 3],
       [5, 6, 7]])

In [135]:
a3 = np.arange(27).reshape(3,3,3)
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [136]:
# get 2nd 2D array from a3
a3[1]

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])

In [137]:
# get 1st and last 2D array from a3
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [139]:
# get first 2D array 3 4 5 row in 3D array a3
a3[0,1,:]   # (array position,row,column)

array([3, 4, 5])

In [146]:
# get 2nd 2D array 10 13 16 cols in 3D array a3
a3[1,:,1]

array([10, 13, 16])

In [147]:
# get 3rd 2D array 22 23 25 26 in 3D array a3
a3[2,1:,1:]

array([[22, 23],
       [25, 26]])

In [151]:
# get 1st 0 2 from 3rd 18 20
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

# Iterating

In [152]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [153]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [154]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [155]:
# for 1D
for i in a1:
    print(i)

0
1
2
3
4
5
6
7
8
9


In [156]:
# for 2D -> it's print 1 row each time
for i in a2:
    print(i)

[0 1 2 3]
[4 5 6 7]
[ 8  9 10 11]


In [159]:
# for 3D -> it's print 1 2D array each time
for i in a3:
    print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [160]:
# for 2D -> in order to get indivisual items
for i in np.nditer(a2):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [161]:
# for 3D -> in order to get indivisual items -> first 3D converted to 1D
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


# Reshaping

In [162]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [165]:
# Transpose -> row become col -> col become row
np.transpose(a2) # (3,4) -> (4,3)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [166]:
a2.T # shortcut of transpose

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [167]:
# ravel -> No matter how many dimension arrray we give it convert that to 1D
a2      # it's 2D

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [169]:
a2.ravel()  # 2D -> 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [171]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [172]:
a3.ravel() # 3D -> 1D

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

# Stacking

In [174]:
# horizontal stacking
a4 = np.arange(12).reshape(3,4)
a5 = np.arange(12,24).reshape(3,4)

In [175]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [176]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [177]:
# horizontal stacking   # shape should be shape foe 2 Matrix
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [178]:
# Vertical stacking
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

# Splitting

In [179]:
# horizontal splitting
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [180]:
# horizontal splitting   # can be done only with equal part
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [181]:
# horizontal splitting   # can be done only with equal part
np.hsplit(a4,5)  # not possible since equal part is not coming

ValueError: array split does not result in an equal division

In [182]:
# vertical splitting
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [184]:
np.vsplit(a5,3) # only cut equal

[array([[12, 13, 14, 15]]),
 array([[16, 17, 18, 19]]),
 array([[20, 21, 22, 23]])]

In [185]:
np.vsplit(a5,2) # only cut equal # cant cut in 2 parts 

ValueError: array split does not result in an equal division