# np.sort

Return a sorted copy of an array.

https://numpy.org/doc/stable/reference/generated/numpy.sort.html

In [13]:
# code

import numpy as np
a = np.random.randint(1,100,15)
a

array([22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52])

In [4]:
b = np.random.randint(1,100,24).reshape(6,4)
b

array([[19, 64, 16,  3],
       [52, 40,  8, 41],
       [54, 68, 48, 29],
       [40, 53, 48, 29],
       [26, 88, 89, 78],
       [94, 44, 52, 13]])

In [14]:
# sort function # default Ascending

np.sort(a)

array([ 3,  5, 14, 17, 22, 33, 40, 43, 44, 52, 57, 65, 69, 75, 77])

In [17]:
# in order to get in descending order
np.sort(a)[::-1]

array([77, 75, 69, 65, 57, 52, 44, 43, 40, 33, 22, 17, 14,  5,  3])

In [15]:
np.sort(b) # row wise sorting

array([[ 3, 16, 19, 64],
       [ 8, 40, 41, 52],
       [29, 48, 54, 68],
       [29, 40, 48, 53],
       [26, 78, 88, 89],
       [13, 44, 52, 94]])

In [16]:
np.sort(b, axis = 0) # column wise sorting

array([[19, 40,  8,  3],
       [26, 44, 16, 13],
       [40, 53, 48, 29],
       [52, 64, 48, 29],
       [54, 68, 52, 41],
       [94, 88, 89, 78]])

In [18]:
np.sort(b, axis = 0)[::-1] # column wise sorting Descending

array([[94, 88, 89, 78],
       [54, 68, 52, 41],
       [52, 64, 48, 29],
       [40, 53, 48, 29],
       [26, 44, 16, 13],
       [19, 40,  8,  3]])

# np.append

The numpy.append() appends values along the mentioned axis at the end of the array

https://numpy.org/doc/stable/reference/generated/numpy.append.html


In [19]:
# code
a

array([22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52])

In [20]:
# suppose we want to append 200 at array a
np.append(a,200)

array([ 22,  77,  33,  69,   5,   3,  75,  17,  14,  65,  44,  43,  40,
        57,  52, 200])

In [21]:
b

array([[19, 64, 16,  3],
       [52, 40,  8, 41],
       [54, 68, 48, 29],
       [40, 53, 48, 29],
       [26, 88, 89, 78],
       [94, 44, 52, 13]])

In [54]:
# suppose we want add one more column at the end wit 111111
np.append(b,np.ones((b.shape[0],1)), axis = 1)

array([[19., 64., 16.,  3.,  1.],
       [52., 40.,  8., 41.,  1.],
       [54., 68., 48., 29.,  1.],
       [40., 53., 48., 29.,  1.],
       [26., 88., 89., 78.,  1.],
       [94., 44., 52., 13.,  1.]])

In [24]:
# can also put random item
np.append(b,np.random.random((b.shape[0],1)), axis = 1)

array([[19.        , 64.        , 16.        ,  3.        ,  0.27185271],
       [52.        , 40.        ,  8.        , 41.        ,  0.54319138],
       [54.        , 68.        , 48.        , 29.        ,  0.92409412],
       [40.        , 53.        , 48.        , 29.        ,  0.18468108],
       [26.        , 88.        , 89.        , 78.        ,  0.69498033],
       [94.        , 44.        , 52.        , 13.        ,  0.20613404]])

# np.concatenate

numpy.concatenate() function concatenate a sequence of arrays along an existing axis.

https://numpy.org/doc/stable/reference/generated/numpy.concatenate.html

In [25]:
# code
c = np.arange(6).reshape(2,3)
d = np.arange(6,12).reshape(2,3)

print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [27]:
np.concatenate((c,d), axis = 0)  # col wise conctenation

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
np.concatenate((c,d), axis = 1) # row wise conctenation

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

# np.unique

With the help of np.unique() method, we can get the unique values from an array given as parameter in np.unique() method.

https://numpy.org/doc/stable/reference/generated/numpy.unique.html/

In [29]:
# code
e = np.array([1,1,2,2,3,3,4,4,5,5,6,6])
e

array([1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 6])

In [30]:
np.unique(e)

array([1, 2, 3, 4, 5, 6])

# np.expand_dims

With the help of Numpy.expand_dims() method, we can get the expanded dimensions of an array

https://numpy.org/doc/stable/reference/generated/numpy.expand_dims.html

In [31]:
# code
a.shape  

(15,)

In [40]:
# our a is 1D converting it to 2D   # row vector
np.expand_dims(a, axis = 0) #  row wise

array([[22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52]])

In [38]:
 # our a is 1D converting it to 2D
np.expand_dims(a, axis = 0).shape  #  row wise

(1, 15)

In [41]:
# our a is 1D converting it to 2D  # column vector
np.expand_dims(a, axis = 1) # col wise

array([[22],
       [77],
       [33],
       [69],
       [ 5],
       [ 3],
       [75],
       [17],
       [14],
       [65],
       [44],
       [43],
       [40],
       [57],
       [52]])

In [39]:
np.expand_dims(a, axis = 1).shape  # col wise

(15, 1)

# np.where

The numpy.where() function returns the indices of elements in an input array where the given condition is satisfied.

https://numpy.org/doc/stable/reference/generated/numpy.where.html

In [42]:
a 

array([22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52])

In [45]:
# find all indices with value greater than 50
np.where(a > 50)

(array([ 1,  3,  6,  9, 13, 14], dtype=int64),)

In [46]:
# replace all values > 50 with 0
np.where(a > 50, 0, a)

array([22,  0, 33,  0,  5,  3,  0, 17, 14,  0, 44, 43, 40,  0,  0])

In [47]:
# if number is even replace it with 0
np.where(a % 2 == 0, 0, a)

array([ 0, 77, 33, 69,  5,  3, 75, 17,  0, 65,  0, 43,  0, 57,  0])

# np.argmax

The numpy.argmax() function returns indices of the max element of the array in a particular axis.

https://numpy.org/doc/stable/reference/generated/numpy.argmax.html

In [48]:
# code
a

array([22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52])

In [49]:
# suppose inside a we want to get biggest values index position
np.argmax(a)

1

In [50]:
b

array([[19, 64, 16,  3],
       [52, 40,  8, 41],
       [54, 68, 48, 29],
       [40, 53, 48, 29],
       [26, 88, 89, 78],
       [94, 44, 52, 13]])

In [51]:
# col wise max
np.argmax(b, axis = 0)

array([5, 4, 4, 4], dtype=int64)

In [52]:
# row wise max
np.argmax(b, axis = 1)

array([1, 0, 1, 1, 2, 0], dtype=int64)

In [55]:
# np.argmin
a

array([22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52])

In [56]:
# in order to get mimium item index
np.argmin(a)

5

# np.cumsum

numpy.cumsum() function is used when we want to compute the cumulative sum of array elements over a given axis.

https://numpy.org/doc/stable/reference/generated/numpy.cumsum.html

In [57]:
  a

array([22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52])

In [58]:
# cumulative sum
np.cumsum(a)

array([ 22,  99, 132, 201, 206, 209, 284, 301, 315, 380, 424, 467, 507,
       564, 616])

In [59]:
b

array([[19, 64, 16,  3],
       [52, 40,  8, 41],
       [54, 68, 48, 29],
       [40, 53, 48, 29],
       [26, 88, 89, 78],
       [94, 44, 52, 13]])

In [61]:
np.cumsum(b)  # since no axis given it's converted to 1D

array([  19,   83,   99,  102,  154,  194,  202,  243,  297,  365,  413,
        442,  482,  535,  583,  612,  638,  726,  815,  893,  987, 1031,
       1083, 1096])

In [62]:
np.cumsum(b, axis = 0) # col wise

array([[ 19,  64,  16,   3],
       [ 71, 104,  24,  44],
       [125, 172,  72,  73],
       [165, 225, 120, 102],
       [191, 313, 209, 180],
       [285, 357, 261, 193]])

In [63]:
np.cumsum(b, axis = 1) # row wise

array([[ 19,  83,  99, 102],
       [ 52,  92, 100, 141],
       [ 54, 122, 170, 199],
       [ 40,  93, 141, 170],
       [ 26, 114, 203, 281],
       [ 94, 138, 190, 203]])

In [65]:
# np.cumprod
a

array([22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52])

In [66]:
np.cumprod(a)  # product

array([         22,        1694,       55902,     3857238,    19286190,
          57858570,    44425454,   755232718,  1983323460,    67006020,
       -1346702416, -2073629040, -1340782976,   884781696, -1235992064])

# np.percentile

numpy.percentile()function used to compute the nth percentile of the given data (array elements) along the specified axis. 

https://numpy.org/doc/stable/reference/generated/numpy.percentile.html

In [67]:
a

array([22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52])

In [68]:
np.percentile(a,100) # 77 since in a no one is above 77 MAX

77.0

In [69]:
np.percentile(a,0)  # 3 since minimum value in a 

3.0

In [70]:
np.percentile(a,50) # median 50-50

43.0

In [72]:
np.median(a) # median :)

43.0

# np.histogram

Numpy has a built-in numpy.histogram() function which represents the frequency of data distribution in the graphical form.

https://numpy.org/doc/stable/reference/generated/numpy.histogram.html

In [73]:
# code
a

array([22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52])

In [75]:
np.histogram(a, bins = [0,10,20,30,40,50,60,70,80,90,100])

(array([2, 2, 1, 1, 3, 2, 2, 2, 0, 0], dtype=int64),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [76]:
# making small bins size
np.histogram(a, bins = [0,50,100])

(array([9, 6], dtype=int64), array([  0,  50, 100]))

# np.corrcoef

Return Pearson product-moment correlation coefficients.

https://numpy.org/doc/stable/reference/generated/numpy.corrcoef.html

In [77]:
salary = np.array([20000,40000,25000,35000,60000])
experience = np.array([1,3,2,4,2])

np.corrcoef(salary,experience)

array([[1.        , 0.25344572],
       [0.25344572, 1.        ]])

# np.isin

With the help of numpy.isin() method, we can see that one array having values are checked in a different numpy array having different elements with different sizes.

https://numpy.org/doc/stable/reference/generated/numpy.isin.html

In [78]:
# code
a

array([22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52])

In [80]:
items = [10,20,30,40,50,60,70,80,90,100]
a[np.isin(a,items)]

array([40])

# np.flip

The numpy.flip() function reverses the order of array elements along the specified axis, preserving the shape of the array.

https://numpy.org/doc/stable/reference/generated/numpy.flip.html

In [81]:
# code
a

array([22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52])

In [82]:
np.flip(a) # mirror image first become last

array([52, 57, 40, 43, 44, 65, 14, 17, 75,  3,  5, 69, 33, 77, 22])

In [83]:
b

array([[19, 64, 16,  3],
       [52, 40,  8, 41],
       [54, 68, 48, 29],
       [40, 53, 48, 29],
       [26, 88, 89, 78],
       [94, 44, 52, 13]])

In [84]:
np.flip(b) # row and col wise flip

array([[13, 52, 44, 94],
       [78, 89, 88, 26],
       [29, 48, 53, 40],
       [29, 48, 68, 54],
       [41,  8, 40, 52],
       [ 3, 16, 64, 19]])

In [85]:
np.flip(b, axis = 0) # col wise flip

array([[94, 44, 52, 13],
       [26, 88, 89, 78],
       [40, 53, 48, 29],
       [54, 68, 48, 29],
       [52, 40,  8, 41],
       [19, 64, 16,  3]])

In [86]:
np.flip(b, axis = 1) # row wise flip

array([[ 3, 16, 64, 19],
       [41,  8, 40, 52],
       [29, 48, 68, 54],
       [29, 48, 53, 40],
       [78, 89, 88, 26],
       [13, 52, 44, 94]])

# np.put

The numpy.put() function replaces specific elements of an array with given values of p_array. Array indexed works on flattened array. 

https://numpy.org/doc/stable/reference/generated/numpy.put.html

In [87]:
#  code
a

array([22, 77, 33, 69,  5,  3, 75, 17, 14, 65, 44, 43, 40, 57, 52])

In [88]:
# suppose we want to chang 1st and 2nd item from a
np.put(a,[0,1],[110,530])    # it's do permanent changes so we won't see any output

In [89]:
# in order to see changes
a

array([110, 530,  33,  69,   5,   3,  75,  17,  14,  65,  44,  43,  40,
        57,  52])

# np.delete

The numpy.delete() function returns a new array with the deletion of sub-arrays along with the mentioned axis. 

https://numpy.org/doc/stable/reference/generated/numpy.delete.html

In [90]:
# code
a

array([110, 530,  33,  69,   5,   3,  75,  17,  14,  65,  44,  43,  40,
        57,  52])

In [92]:
# suppose we want to delete 110 from a
np.delete(a,0) # all we need to provide index

array([530,  33,  69,   5,   3,  75,  17,  14,  65,  44,  43,  40,  57,
        52])

In [93]:
# Deleteing multiple items
np.delete(a,[0,2,4])

array([530,  69,   3,  75,  17,  14,  65,  44,  43,  40,  57,  52])

# Set functions

- np.union1d
- np.intersect1d
- np.setdiff1d
- np.setxor1d
- np.in1d

In [95]:
m = np.array([1,2,3,4,5])
n = np.array([3,4,5,6,7])

In [96]:
# to get union
np.union1d(m,n) # only unique values are allowed

array([1, 2, 3, 4, 5, 6, 7])

In [97]:
# intersect
np.intersect1d(m,n) # only common vallues are alowed 

array([3, 4, 5])

In [98]:
# shows item are in m bt not in n
np.setdiff1d(m,n)

array([1, 2])

In [99]:
# setdiff1d -> shows item are in n bt not in m
np.setdiff1d(n,m)

array([6, 7])

In [100]:
# xor -> it will show only uncommon of both m and n
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [102]:
# in1d -> shows in a given set item are present or not like membership operator
np.in1d(m,1)

array([ True, False, False, False, False])

In [104]:
m[np.in1d(m,1)]

array([1])

In [103]:
# in1d -> shows in a given set item are present or not like membership operator
np.in1d(m,10)

array([False, False, False, False, False])

# np.clip

numpy.clip() function is used to Clip (limit) the values in an array.

https://numpy.org/doc/stable/reference/generated/numpy.clip.html

In [105]:
# code
a

array([110, 530,  33,  69,   5,   3,  75,  17,  14,  65,  44,  43,  40,
        57,  52])

In [106]:
np.clip(a,a_min=25,a_max=75) # higher and lower values cliped with 75 and 25 repectively rest as it is.

array([75, 75, 33, 69, 25, 25, 75, 25, 25, 65, 44, 43, 40, 57, 52])

In [ ]:
# 17. np.swapaxes

In [ ]:
# 18. np.uniform

In [ ]:
# 19. np.count_nonzero

In [ ]:
# 21. np.tile
# https://www.kaggle.com/code/abhayparashar31/best-numpy-functions-for-data-science-50?scriptVersionId=98816580

In [ ]:
# 22. np.repeat
# https://towardsdatascience.com/10-numpy-functions-you-should-know-1dc4863764c5

In [ ]:

# 25. np.allclose and equals